spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/todo_db
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  threads:
    virtual:
      enabled: true

server:
  port: ${PORT:8080}

cors:
  allowed-origins: ${FRONTEND_URL:http://localhost:5173}
